### ISSUE TITLE
node app.js这个命令执行报错

### ISSUE THREAD

**Issue by duanduan2288** [tangguangyao/stock#1]
执行node app.js这个命令的时候报下面的错误

/var/www/yjf/stock/node_modules/connect-mongo/src/index.js:3
const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/yjf/stock/node_modules/connect-mongo/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by dengnan123** [comment]
throw new Error('Connection strategy not found');
                ^

Error: Connection strategy not found
    at MongoStore (C:\Users\Administrator\Desktop\各种项目\stock-master\node_modules\connect-mongo\src\index.js:105:23)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\各种项目\stock-master\app.js:37:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

Process finished with exit code 1

**Comment by woaer** [comment]
这个项目怕是不维护了，我也是启动不了，建议作者在 `package.json` 中指定依赖的包的版本号，好多 api 都已经不支持了，启动各种报错。
